const e=JSON.parse('{"key":"v-75be2b40","path":"/python-core/errors/sqlalchemy-lost-connection.html","title":"SQLAlchemy 连接池中的连接失效","lang":"zh-CN","frontmatter":{},"headers":[{"level":2,"title":"1. 问题复现","slug":"_1-问题复现","link":"#_1-问题复现","children":[]},{"level":2,"title":"2. 解决方案","slug":"_2-解决方案","link":"#_2-解决方案","children":[{"level":3,"title":"2.1 不使用连接池","slug":"_2-1-不使用连接池","link":"#_2-1-不使用连接池","children":[]},{"level":3,"title":"2.2 设置连接超时时间","slug":"_2-2-设置连接超时时间","link":"#_2-2-设置连接超时时间","children":[]},{"level":3,"title":"2.3 自动重连","slug":"_2-3-自动重连","link":"#_2-3-自动重连","children":[]}]}],"git":{"updatedTime":1696175147000,"contributors":[{"name":"Sun-ZhenXing","email":"1006925066@qq.com","commits":3}]},"filePathRelative":"python-core/errors/sqlalchemy-lost-connection.md","excerpt":""}');export{e as data};
